-- H2 (MySQL compatibility mode) schema for local Spring Boot / tests

CREATE TABLE company (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE major (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL UNIQUE,
    is_cs_related   BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE degree (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL UNIQUE,
    sort_order  INT NOT NULL UNIQUE
);

CREATE TABLE skill (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_key   VARCHAR(50) NOT NULL UNIQUE,
    skill_name  VARCHAR(100) NOT NULL
);

CREATE TABLE position_type (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(30) NOT NULL UNIQUE,
    name        VARCHAR(50) NOT NULL
);

CREATE TABLE stage (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT NOT NULL,
    name        VARCHAR(50) NOT NULL,
    sort_order  INT NOT NULL,
    CONSTRAINT fk_stage_company FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT uq_stage_company_order UNIQUE (company_id, sort_order),
    CONSTRAINT uq_stage_company_name  UNIQUE (company_id, name),
    CONSTRAINT uq_stage_id_company UNIQUE (id, company_id)
);

CREATE TABLE status (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(30) NOT NULL UNIQUE,
    name        VARCHAR(50) NOT NULL
);

CREATE TABLE applicant (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL,
    email       VARCHAR(200) NOT NULL,
    birth_date  DATE,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE education (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_id  BIGINT NOT NULL,
    school_name   VARCHAR(100) NOT NULL,
    degree_id     BIGINT NOT NULL,
    major_id      BIGINT NOT NULL,
    CONSTRAINT fk_edu_applicant FOREIGN KEY (applicant_id) REFERENCES applicant(id),
    CONSTRAINT fk_edu_degree FOREIGN KEY (degree_id) REFERENCES degree(id),
    CONSTRAINT fk_edu_major FOREIGN KEY (major_id) REFERENCES major(id),
    CONSTRAINT uq_education_applicant_degree UNIQUE (applicant_id, degree_id)
);

CREATE TABLE career (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_id      BIGINT NOT NULL,
    company_name      VARCHAR(100) NOT NULL,
    years             DECIMAL(4,1) NOT NULL,
    position_type_id  BIGINT NOT NULL,
    is_current        BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_career_applicant FOREIGN KEY (applicant_id) REFERENCES applicant(id),
    CONSTRAINT fk_career_position FOREIGN KEY (position_type_id) REFERENCES position_type(id),
    CONSTRAINT chk_career_years CHECK (years > 0)
);

CREATE TABLE career_skill (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    career_id   BIGINT NOT NULL,
    skill_id    BIGINT NOT NULL,
    CONSTRAINT fk_cs_career FOREIGN KEY (career_id) REFERENCES career(id),
    CONSTRAINT fk_cs_skill FOREIGN KEY (skill_id) REFERENCES skill(id),
    CONSTRAINT uq_career_skill UNIQUE (career_id, skill_id)
);

CREATE TABLE job_posting (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id        BIGINT NOT NULL,
    title             VARCHAR(200) NOT NULL,
    position_type_id  BIGINT NOT NULL,
    is_active         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_jp_company FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT fk_jp_position FOREIGN KEY (position_type_id) REFERENCES position_type(id),
    CONSTRAINT uq_job_posting_id_company UNIQUE (id, company_id)
);

CREATE TABLE job_posting_skill (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id  BIGINT NOT NULL,
    skill_id        BIGINT NOT NULL,
    CONSTRAINT fk_jps_job FOREIGN KEY (job_posting_id) REFERENCES job_posting(id),
    CONSTRAINT fk_jps_skill FOREIGN KEY (skill_id) REFERENCES skill(id),
    CONSTRAINT uq_job_posting_skill UNIQUE (job_posting_id, skill_id)
);

CREATE TABLE application (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL,
    job_posting_id  BIGINT NOT NULL,
    applicant_id    BIGINT NOT NULL,
    stage_id        BIGINT NOT NULL,
    status_id       BIGINT NOT NULL,
    applied_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_app_company FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT fk_app_applicant FOREIGN KEY (applicant_id) REFERENCES applicant(id),
    CONSTRAINT fk_app_status FOREIGN KEY (status_id) REFERENCES status(id),
    CONSTRAINT fk_app_job_company
        FOREIGN KEY (job_posting_id, company_id) REFERENCES job_posting(id, company_id),
    CONSTRAINT fk_app_stage_company
        FOREIGN KEY (stage_id, company_id) REFERENCES stage(id, company_id),
    CONSTRAINT uq_application_company_job_applicant UNIQUE (company_id, job_posting_id, applicant_id)
);

CREATE TABLE app_history (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id   BIGINT NOT NULL,
    from_stage_id    BIGINT,
    to_stage_id      BIGINT NOT NULL,
    from_status_id   BIGINT,
    to_status_id     BIGINT NOT NULL,
    reason           VARCHAR(500),
    changed_by       VARCHAR(100),
    changed_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ah_app FOREIGN KEY (application_id) REFERENCES application(id),
    CONSTRAINT fk_ah_from_stage FOREIGN KEY (from_stage_id) REFERENCES stage(id),
    CONSTRAINT fk_ah_to_stage FOREIGN KEY (to_stage_id) REFERENCES stage(id),
    CONSTRAINT fk_ah_from_status FOREIGN KEY (from_status_id) REFERENCES status(id),
    CONSTRAINT fk_ah_to_status FOREIGN KEY (to_status_id) REFERENCES status(id)
);

CREATE TABLE app_user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT NOT NULL,
    email       VARCHAR(200) NOT NULL,
    name        VARCHAR(50) NOT NULL,
    CONSTRAINT fk_user_company FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT uq_app_user_company_email UNIQUE (company_id, email)
);

CREATE TABLE role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(30) NOT NULL UNIQUE,
    name        VARCHAR(50) NOT NULL
);

CREATE TABLE user_role (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT NOT NULL,
    role_id  BIGINT NOT NULL,
    CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES role(id),
    CONSTRAINT uq_user_role UNIQUE (user_id, role_id)
);

CREATE INDEX idx_job_posting_company_position
    ON job_posting (company_id, position_type_id, is_active);
CREATE INDEX idx_application_company_job_stage_status
    ON application (company_id, job_posting_id, stage_id, status_id);
CREATE INDEX idx_application_company_stage_status_job_applicant
    ON application (company_id, stage_id, status_id, job_posting_id, applicant_id);
CREATE INDEX idx_education_applicant_degree_major
    ON education (applicant_id, degree_id, major_id);
CREATE INDEX idx_career_applicant_position
    ON career (applicant_id, position_type_id);
CREATE INDEX idx_career_skill_skill_career
    ON career_skill (skill_id, career_id);
